### ISSUE TITLE
invalid free in singleStage for android

### ISSUE THREAD

**Issue by mgood7123** [jniemann66/ReSampler#12]
```
srconvert.h:266
Converter<float>::initSinglestage() A/libc: Invalid address 0x7df8ce8000 passed to free: value not allocated
```

**Comment by jniemann66** [comment]
This is probably the same bug as the multistage bug (#13), which should have been resolved
I tested it on Windows with 32-bit, No SSE (for scalar operation) with --singleStage
and it worked ok.

Let me know how you go with it ...

**Comment by mgood7123** [comment]
ok, ill let you know if it works when I finish cloning my fork in Android Studio
