### ISSUE TITLE
account for android when printing progress

### ISSUE THREAD

**Issue by mgood7123** [jniemann66/ReSampler#21]
https://github.com/jniemann66/ReSampler/blob/3d868ef0ea57e5c40ed5529506f57494eda1bae0/ReSampler.cpp#L759

				std::cout << progressPercentage << "%"
				#ifndef COMPILING_ON_ANDROID
				<< "\b\b\b"
				#endif
				<< std::flush;

**Comment by jniemann66** [comment]
Yeah I was thinking of adding a callback for this. Maybe something like
 **ReSampler::setProgressUpdateHandler(std::function<void(int)> progressFunc)**

**Comment by mgood7123** [comment]
ok

**Comment by jniemann66** [comment]
I started putting this together in dev branch. Seems to work but needs more testing etc

**Comment by jniemann66** [comment]
closing.
